<?php

namespace Database\Seeders;

use App\Models\NewsArticle;
use Illuminate\Database\Seeder;

class NewsArticleSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            [
                'title'        => 'Что не так с государственными закупками в Узбекистане',
                'excerpt'      => 'Обзор ключевых проблем системы госзакупок: от непрозрачных тендеров до отсутствия реальной конкуренции.',
                'content'      => 'Подробный разбор системных проблем государственных закупок Узбекистана — коррупционные риски, монополизация тендеров и пути их решения.',
                'image'        => 'news/seed_1.png',
                'is_featured'  => true,
                'category'     => 'analytics',
                'source'       => 'spot.uz',
                'source_url'   => 'https://www.spot.uz/ru/2022/05/06/public-purchases-/',
                'tags'         => ['госзакупки', 'реформа', 'прозрачность'],
                'views'        => 1540,
                'published_at' => '2022-05-08',
                'translations' => [
                    'uz' => [
                        'title'   => 'O\'zbekistonda davlat xaridlarida nima noto\'g\'ri',
                        'excerpt' => 'Davlat xaridlari tizimining asosiy muammolariga sharh.',
                        'content' => 'O\'zbekiston davlat xaridlarining tizimli muammolarini batafsil ko\'rib chiqish.',
                    ],
                    'en' => [
                        'title'   => 'What is wrong with public procurement in Uzbekistan',
                        'excerpt' => 'Overview of key problems in the public procurement system.',
                        'content' => 'Detailed analysis of systemic problems in Uzbekistan\'s public procurement.',
                    ],
                ],
            ],
            [
                'title'        => 'Как в Узбекистане ограничивают бизнес в тендерах и что с этим делать. Мнение эксперта',
                'excerpt'      => 'Эксперт рассказывает о реальных механизмах ограничения бизнеса в государственных тендерах и о том, что нужно изменить.',
                'content'      => 'Интервью с экспертом о практических аспектах ограничений для бизнеса в тендерах Узбекистана.',
                'image'        => 'news/seed_2.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'podrobno.uz',
                'source_url'   => 'https://podrobno.uz/cat/economic/kak-v-uzbekistane-ogranichivayut-biznes-v-tenderakh-i-chto-s-etim-delat-mnenie-eksperta-/',
                'tags'         => ['тендер', 'бизнес', 'эксперт'],
                'views'        => 870,
                'published_at' => '2022-10-26',
                'translations' => [
                    'uz' => [
                        'title'   => 'O\'zbekistonda tenderlarda biznesni qanday cheklashadi va bu bilan nima qilish kerak. Ekspert fikri',
                        'excerpt' => 'Ekspert davlat tenderlarida biznesni cheklashning real mexanizmlari haqida gapiradi.',
                        'content' => 'O\'zbekistonda tenderlarda biznesni cheklash amaliyotining batafsil tahlili.',
                    ],
                    'en' => [
                        'title'   => 'How business is restricted in tenders in Uzbekistan and what to do about it. Expert opinion',
                        'excerpt' => 'An expert talks about real mechanisms for restricting business in public tenders.',
                        'content' => 'Interview with an expert on practical aspects of business restrictions in Uzbekistan tenders.',
                    ],
                ],
            ],
            [
                'title'        => 'Как агрегатор TenderZone помогает компаниям при участии в тендерах',
                'excerpt'      => 'Разбор функциональности платформы TenderZone — агрегатора тендерных объявлений, упрощающего поиск и участие в закупочных процедурах.',
                'content'      => 'Детальный обзор платформы TenderZone: как она агрегирует тендеры, какие инструменты предоставляет поставщикам и заказчикам.',
                'image'        => 'news/seed_3.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'spot.uz',
                'source_url'   => 'https://www.spot.uz/ru/2022/10/19/tender-zone/',
                'tags'         => ['TenderZone', 'платформа', 'тендер'],
                'views'        => 760,
                'published_at' => '2022-10-19',
                'translations' => [
                    'uz' => [
                        'title'   => 'TenderZone agregatori kompaniyalarga tenderlarda ishtirok etishda qanday yordam beradi',
                        'excerpt' => 'TenderZone platformasining funksionalligini ko\'rib chiqish.',
                        'content' => 'TenderZone platformasining batafsil sharhi.',
                    ],
                    'en' => [
                        'title'   => 'How TenderZone aggregator helps companies participate in tenders',
                        'excerpt' => 'Analysis of TenderZone platform functionality.',
                        'content' => 'Detailed review of the TenderZone platform.',
                    ],
                ],
            ],
            [
                'title'        => 'Как ущемляются права отечественных производителей на кооперационном портале cooperation.uz. Мнение эксперта',
                'excerpt'      => 'Анализ нарушений прав местных производителей на корпоративном закупочном портале и их влияния на конкуренцию.',
                'content'      => 'Обзор проблем отечественных производителей на портале cooperation.uz и практические последствия этих нарушений.',
                'image'        => 'news/seed_4.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'podrobno.uz',
                'source_url'   => 'https://podrobno.uz/cat/obchestvo/kak-ushchemlyayutsya-prava-otechestvennykh-proizvoditeley-na-kooperatsionnom-portale-cooperation-uz-/',
                'tags'         => ['cooperation.uz', 'производители', 'реформа'],
                'views'        => 590,
                'published_at' => '2023-04-05',
                'translations' => [
                    'uz' => [
                        'title'   => 'Mahalliy ishlab chiqaruvchilar huquqlari cooperation.uz korporativ portali orqali qanday buzilmoqda. Ekspert fikri',
                        'excerpt' => 'Mahalliy ishlab chiqaruvchilar huquqlaridagi buzilishlarni tahlil qilish.',
                        'content' => 'cooperation.uz portalida mahalliy ishlab chiqaruvchilar muammolariga sharh.',
                    ],
                    'en' => [
                        'title'   => 'How rights of domestic manufacturers are violated on cooperation.uz portal. Expert opinion',
                        'excerpt' => 'Analysis of violations of local manufacturers\' rights on the corporate procurement portal.',
                        'content' => 'Overview of problems of domestic manufacturers on the cooperation.uz portal.',
                    ],
                ],
            ],
            [
                'title'        => 'Nazorat yo\'q, alohida vakolatli organ yetishmaydi, raqobatsiz savdolar va ortiqcha pul-davri — Davlat xaridlari tizimi islohotga muhtoj(mi?)',
                'excerpt'      => 'Разбор механизмов участия иностранных компаний в узбекских тендерах и возможных рисков для местных поставщиков.',
                'content'      => 'Анализ практики участия иностранных игроков в тендерах Узбекистана на примере конкретных случаев.',
                'image'        => 'news/seed_5.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'daryo.uz',
                'source_url'   => 'https://daryo.uz/2023/06/13/nazorat-yoq-alohida-vakolatli-organ-yetishmaydi-raqobatsiz-savdolar-va-ortiqcha-garov-puli-davlat-xaridlari-tizimi-islohotga-muhtojmi/',
                'tags'         => ['реформа', 'надзор', 'госзакупки'],
                'views'        => 1020,
                'published_at' => '2023-06-13',
                'translations' => [
                    'uz' => [
                        'title'   => 'Nazorat yo\'q, alohida vakolatli organ yetishmaydi, raqobatsiz savdolar va ortiqcha pul-davri — Davlat xaridlari tizimi islohotga muhtoj(mi?)',
                        'excerpt' => 'Davlat xaridlari tizimidagi nazorat va raqobat muammolarini ko\'rib chiqish.',
                        'content' => 'O\'zbekiston tenderlarida nazorat va raqobat muammolarini tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'No oversight, no dedicated authority, non-competitive trading — does the public procurement system need reform?',
                        'excerpt' => 'Analysis of oversight and competition problems in the public procurement system.',
                        'content' => 'Analysis of oversight and competition problems in Uzbekistan tenders.',
                    ],
                ],
            ],
            [
                'title'        => 'Davlat xaridlari buyurtmachilari tadbirkorlar doirasini sun\'iy qisqartirishda davom etmoqda. Qanday qilib?',
                'excerpt'      => 'Как заказчики искусственно сужают круг участников тендеров, нарушая принципы честной конкуренции.',
                'content'      => 'Детальный анализ методов, которыми государственные заказчики ограничивают конкуренцию в закупочных процедурах.',
                'image'        => 'news/seed_6.png',
                'is_featured'  => false,
                'category'     => 'investigation',
                'source'       => 'daryo.uz',
                'source_url'   => 'https://daryo.uz/2023/07/20/davlat-xaridlari-buyurtmachilari-tadbirkorlar-doirasini-suniy-qisqartirishda-davom-etmoqda-qanday-qilib',
                'tags'         => ['тендер', 'конкуренция', 'расследование'],
                'views'        => 680,
                'published_at' => '2023-07-20',
                'translations' => [
                    'uz' => [
                        'title'   => 'Davlat xaridlari buyurtmachilari tadbirkorlar doirasini sun\'iy qisqartirishda davom etmoqda. Qanday qilib?',
                        'excerpt' => 'Buyurtmachilar tender ishtirokchilarini qanday qilib sun\'iy ravishda qisqartirayotganini ko\'rib chiqish.',
                        'content' => 'Davlat buyurtmachilari xarid jarayonlarida raqobatni qanday cheklayotganini batafsil tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'Public procurement customers continue to artificially narrow the circle of entrepreneurs. How?',
                        'excerpt' => 'How customers artificially narrow the circle of tender participants, violating fair competition principles.',
                        'content' => 'Detailed analysis of methods state customers use to restrict competition in procurement procedures.',
                    ],
                ],
            ],
            [
                'title'        => 'Власти ввели лимит на покупку народного бензина АИ-80 на бирже. Это грозит повышением цен и дефицитом',
                'excerpt'      => 'Введение ограничений на биржевые закупки топлива АИ-80 может привести к дефициту и росту цен на рынке.',
                'content'      => 'Анализ последствий введения лимитов на покупку бензина АИ-80 на бирже для рынка и потребителей.',
                'image'        => 'news/seed_7.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'podrobno.uz',
                'source_url'   => 'https://podrobno.uz/cat/obchestvo/vlasti-vveli-limit-na-pokupku-narodnogo-benzina-ai-80-na-birzhe-eto-grozit-povysheniem-tsen-i-defits/',
                'tags'         => ['биржа', 'бензин', 'цены'],
                'views'        => 1180,
                'published_at' => '2023-10-19',
                'translations' => [
                    'uz' => [
                        'title'   => 'Hukumat birjada AI-80 xalq benzinini sotib olishga limit kiritdi. Bu narxlarning oshishi va tanqislikka olib kelishi mumkin',
                        'excerpt' => 'AI-80 yonilg\'isini birja xaridlariga cheklovlar joriy etilishi bozorda tanqislik va narx o\'sishiga olib kelishi mumkin.',
                        'content' => 'Birjada AI-80 benzinini sotib olishga limitlar joriy etilishining oqibatlarini tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'Authorities introduced a limit on purchasing AI-80 gasoline on the exchange. This threatens price increases and shortages',
                        'excerpt' => 'Introducing restrictions on exchange purchases of AI-80 fuel may lead to shortages and price increases.',
                        'content' => 'Analysis of the consequences of introducing limits on purchasing AI-80 gasoline on the exchange.',
                    ],
                ],
            ],
            [
                'title'        => 'Госзакупки в новом свете: местное ПО vs. зарубежная зависимость',
                'excerpt'      => 'Анализ проблемы технологической зависимости в государственных закупках программного обеспечения и аргументы за переход на отечественные решения.',
                'content'      => 'Анализ проблемы технологической зависимости государства от иностранного программного обеспечения.',
                'image'        => 'news/seed_8.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'anhor.uz',
                'source_url'   => 'https://anhor.uz/vzglyad-iznutri/software/',
                'tags'         => ['ПО', 'ИИ', 'реформа'],
                'views'        => 890,
                'published_at' => '2025-03-30',
                'translations' => [
                    'uz' => [
                        'title'   => 'Davlat xaridlari yangi nuqtai nazardan: mahalliy dasturiy ta\'minot vs. xorijiy qaramlik',
                        'excerpt' => 'Davlat dasturiy ta\'minot xaridlarida texnologik qaramlik muammosi tahlili.',
                        'content' => 'Davlatning xorijiy dasturiy ta\'minotga texnologik qaramligi muammosi tahlili.',
                    ],
                    'en' => [
                        'title'   => 'Public procurement in new light: local software vs. foreign dependency',
                        'excerpt' => 'Analysis of technological dependency in government software procurement.',
                        'content' => 'Analysis of the state\'s technological dependency on foreign software.',
                    ],
                ],
            ],
            [
                'title'        => '«Необходимо им дать зубы»: эксперт в сфере госзакупок о наблюдательной роли Антикоррупционного агентства и Антимонопольного комитета',
                'excerpt'      => 'Почему надзорные органы не могут эффективно контролировать закупочный рынок и что нужно изменить на законодательном уровне.',
                'content'      => 'Интервью с экспертом о недостатках действующей системы надзора за государственными закупками.',
                'image'        => 'news/seed_9.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'anhor.uz',
                'source_url'   => 'https://anhor.uz/vzglyad-iznutri/role-of-agencies/',
                'tags'         => ['надзор', 'реформа', 'коррупция'],
                'views'        => 640,
                'published_at' => '2025-06-26',
                'translations' => [
                    'uz' => [
                        'title'   => '«Ularga tish berish kerak»: davlat xaridlari sohasidagi ekspert Korrupsiyaga qarshi agentlik va Monopoliyaga qarshi qo\'mitaning kuzatuv roli haqida',
                        'excerpt' => 'Nima uchun nazorat organlari xarid bozorini samarali nazorat qila olmaydi.',
                        'content' => 'Davlat xaridlari ustidan amaldagi nazorat tizimidagi kamchiliklar haqida ekspert bilan suhbat.',
                    ],
                    'en' => [
                        'title'   => '"They need to be given teeth": expert in public procurement on the supervisory role of the Anti-Corruption Agency and Antimonopoly Committee',
                        'excerpt' => 'Why oversight bodies cannot effectively control the procurement market.',
                        'content' => 'Interview with an expert about shortcomings of the current oversight system for public procurement.',
                    ],
                ],
            ],
            [
                'title'        => 'Как реформировать госзакупки в Узбекистане: проблемы, риски и пути решения',
                'excerpt'      => 'Системный анализ действующей закупочной системы — от правовых пробелов до отсутствия независимого контроля и монополизации тендеров.',
                'content'      => 'Системный анализ действующей закупочной системы Узбекистана с предложениями по реформированию.',
                'image'        => 'news/seed_10.png',
                'is_featured'  => true,
                'category'     => 'legislation',
                'source'       => 'mjdc.uz',
                'source_url'   => 'https://mjdc.uz/data-ru/tpost/5d1lcf5mv1-kak-reformirovat-goszakupki-v-uzbekistan',
                'tags'         => ['реформа', 'законодательство', 'TenderZone'],
                'views'        => 1580,
                'published_at' => '2025-07-07',
                'translations' => [
                    'uz' => [
                        'title'   => 'O\'zbekistonda davlat xaridlarini qanday isloh qilish kerak: muammolar, xavflar va yechim yo\'llari',
                        'excerpt' => 'Amaldagi xarid tizimini tizimli tahlil qilish — huquqiy kamchiliklar va monopollashtirish.',
                        'content' => 'O\'zbekistonning amaldagi xarid tizimini isloh bo\'yicha takliflar bilan tizimli tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'How to reform public procurement in Uzbekistan: problems, risks and solutions',
                        'excerpt' => 'Systematic analysis of the current procurement system — from legal gaps to monopolization.',
                        'content' => 'Systematic analysis of Uzbekistan\'s current procurement system with reform proposals.',
                    ],
                ],
            ],
            [
                'title'        => 'В Узбекистане предложили перевести госучреждения на отечественное ПО',
                'excerpt'      => 'Инициатива по замещению иностранного программного обеспечения в государственных структурах на отечественные разработки.',
                'content'      => 'Разбор инициативы по переходу государственных органов на отечественное программное обеспечение.',
                'image'        => 'news/seed_11.png',
                'is_featured'  => false,
                'category'     => 'legislation',
                'source'       => 'spot.uz',
                'source_url'   => 'https://www.spot.uz/ru/2025/07/07/domestic-software/',
                'tags'         => ['ПО', 'импортозамещение', 'реформа'],
                'views'        => 720,
                'published_at' => '2025-07-07',
                'translations' => [
                    'uz' => [
                        'title'   => 'O\'zbekistonda davlat muassasalarini mahalliy dasturiy ta\'minotga o\'tkazish taklif qilindi',
                        'excerpt' => 'Davlat tuzilmalarida xorijiy dasturiy ta\'minotni mahalliy ishlanmalar bilan almashtirish tashabbusi.',
                        'content' => 'Davlat organlarining mahalliy dasturiy ta\'minotga o\'tish tashabbusini ko\'rib chiqish.',
                    ],
                    'en' => [
                        'title'   => 'Uzbekistan proposed transferring government institutions to domestic software',
                        'excerpt' => 'Initiative to replace foreign software in government structures with domestic developments.',
                        'content' => 'Analysis of the initiative for government agencies to transition to domestic software.',
                    ],
                ],
            ],
            [
                'title'        => 'Тендер на $678 тыс. под подозрением: местных отсеяли, иностранцы победили с разницей $27',
                'excerpt'      => 'Детальный разбор конкретного тендера — как требования в документации были сформулированы так, что отечественные компании не смогли пройти отбор.',
                'content'      => 'Детальный разбор тендера на $678 тыс., в котором требования документации фактически исключили местных участников.',
                'image'        => 'news/seed_12.png',
                'is_featured'  => true,
                'category'     => 'investigation',
                'source'       => 'anhor.uz',
                'source_url'   => 'https://anhor.uz/vzglyad-iznutri/tender-678000/',
                'tags'         => ['госзакупки', 'коррупция', 'надзор'],
                'views'        => 3200,
                'published_at' => '2025-07-09',
                'translations' => [
                    'uz' => [
                        'title'   => '$678 ming dollarlik tender shubha ostida: mahalliylar chetlashtirildi, xorijliklar $27 farq bilan g\'alaba qozondi',
                        'excerpt' => 'Hujjatlar talablari mahalliy kompaniyalar qatnasha olmasligi uchun qanday tuzilganini ko\'rsatuvchi tender tahlili.',
                        'content' => '$678 ming dollarlik tender batafsil tahlili.',
                    ],
                    'en' => [
                        'title'   => '$678k tender under suspicion: locals screened out, foreigners won by $27 difference',
                        'excerpt' => 'Analysis of a specific tender showing how documentation requirements effectively excluded local companies.',
                        'content' => 'Detailed analysis of the $678k tender where documentation requirements excluded local participants.',
                    ],
                ],
            ],
            [
                'title'        => 'Поставщик заявил о нарушениях при закупке насосов для BYD Uzbekistan Factory',
                'excerpt'      => 'Местный поставщик оспаривает итоги тендера на закупку промышленного оборудования — история о том, как устроены корпоративные закупки крупных совместных предприятий.',
                'content'      => 'История о нарушениях при проведении закупки промышленного оборудования для BYD Uzbekistan Factory.',
                'image'        => 'news/seed_13.png',
                'is_featured'  => false,
                'category'     => 'investigation',
                'source'       => 'anhor.uz',
                'source_url'   => 'https://anhor.uz/vzglyad-iznutri/byd-uzbekistan/',
                'tags'         => ['BYD', 'тендер', 'биржа'],
                'views'        => 760,
                'published_at' => '2025-10-06',
                'translations' => [
                    'uz' => [
                        'title'   => 'Yetkazib beruvchi BYD Uzbekistan Factory uchun nasos xaridida qonun buzilishlarini e\'lon qildi',
                        'excerpt' => 'Mahalliy yetkazib beruvchi sanoat uskunalari xaridi tenderi natijalariga e\'tiroz bildirmoqda.',
                        'content' => 'BYD Uzbekistan Factory uchun sanoat uskunalari xaridida qonun buzilishlari haqida hikoya.',
                    ],
                    'en' => [
                        'title'   => 'Supplier claimed violations in pump procurement for BYD Uzbekistan Factory',
                        'excerpt' => 'Local supplier disputes results of industrial equipment procurement tender.',
                        'content' => 'Story about violations in procurement of industrial equipment for BYD Uzbekistan Factory.',
                    ],
                ],
            ],
            [
                'title'        => 'ВАК Узбекистана провёл тендер на 564 млн сумов: победителем стала собственная структура',
                'excerpt'      => 'Как государственное ведомство организовало закупку таким образом, что победа оказалась у аффилированной организации — детальный разбор процедуры.',
                'content'      => 'Детальный разбор тендера ВАК Узбекистана на 564 млн сумов, в котором победила структура, аффилированная с самим ведомством.',
                'image'        => 'news/seed_14.png',
                'is_featured'  => true,
                'category'     => 'investigation',
                'source'       => 'anhor.uz',
                'source_url'   => 'https://anhor.uz/vzglyad-iznutri/vak/',
                'tags'         => ['тендер', 'расследование', 'надзор'],
                'views'        => 2100,
                'published_at' => '2025-10-01',
                'translations' => [
                    'uz' => [
                        'title'   => 'O\'zbekiston VAK 564 mln so\'mga tender o\'tkazdi: g\'olib o\'zining tuzilmasi bo\'ldi',
                        'excerpt' => 'Davlat idorasi qanday qilib o\'z tuzilmasi g\'alaba qozonishi uchun xaridni tashkil etganini batafsil tahlil.',
                        'content' => 'O\'zbekiston VAKning 564 mln so\'mga tenderini batafsil tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'Uzbekistan HAC conducted a 564 million sum tender: its own structure won',
                        'excerpt' => 'How a government agency organized procurement so that an affiliated organization won.',
                        'content' => 'Detailed analysis of the HAC Uzbekistan tender for 564 million sums.',
                    ],
                ],
            ],
            [
                'title'        => 'Центр риск-анализа в госзакупках: почему без ИИ бороться с коррупцией невозможно?',
                'excerpt'      => 'Концепция создания аналитического центра с применением искусственного интеллекта для автоматического выявления коррупционных рисков в закупочных процедурах.',
                'content'      => 'Разбор концепции создания аналитического центра с применением ИИ для автоматического выявления коррупционных рисков.',
                'image'        => 'news/seed_15.png',
                'is_featured'  => true,
                'category'     => 'analytics',
                'source'       => 'mjdc.uz',
                'source_url'   => 'https://mjdc.uz/data-ru/tpost/0g3f4lpaa1-tsentr-risk-analiza-v-goszakupkah-pochem',
                'tags'         => ['ИИ', 'коррупция', 'реформа'],
                'views'        => 980,
                'published_at' => '2026-01-05',
                'translations' => [
                    'uz' => [
                        'title'   => 'Davlat xaridlarida xavf tahlili markazi: nima uchun sun\'iy intellektsiz kurash mumkin emas?',
                        'excerpt' => 'Sun\'iy intellektdan foydalanib korrupsion xavflarni avtomatik aniqlash kontseptsiyasi.',
                        'content' => 'Sun\'iy intellektdan foydalanib korrupsion xavflarni aniqlash bo\'yicha tahliliy markazni yaratish kontseptsiyasini ko\'rib chiqish.',
                    ],
                    'en' => [
                        'title'   => 'Risk analysis center in public procurement: why fighting corruption without AI is impossible',
                        'excerpt' => 'Concept of an analytical center using AI to automatically identify corruption risks.',
                        'content' => 'Analysis of the concept of creating an analytical center using AI for automatic detection of corruption risks.',
                    ],
                ],
            ],
            [
                'title'        => 'Новые правила игры на рынке закупок лекарств: сможет ли farma.xarid.uz снизить коррупцию?',
                'excerpt'      => 'Разбор новой платформы для закупок фармацевтической продукции — насколько она способна изменить прозрачность одного из самых коррупционных сегментов госзакупок.',
                'content'      => 'Подробный анализ новой платформы farma.xarid.uz, её функциональности и потенциала для снижения коррупционных рисков в секторе фармацевтических закупок.',
                'image'        => 'news/seed_16.png',
                'is_featured'  => false,
                'category'     => 'analytics',
                'source'       => 'mjdc.uz',
                'source_url'   => 'https://mjdc.uz/data-ru/tpost/r4bcdkf6c1-novie-pravila-igri-na-rinke-zakupok-leka',
                'tags'         => ['госзакупки', 'фарма', 'реформа'],
                'views'        => 1240,
                'published_at' => '2026-02-11',
                'translations' => [
                    'uz' => [
                        'title'   => 'Dorivor vositalar xaridlari bozorida yangi qoidalar: farma.xarid.uz korrupsiyani kamaytira oladimi?',
                        'excerpt' => 'Farmatsevtika mahsulotlarini sotib olish uchun yangi platforma tahlili.',
                        'content' => 'farma.xarid.uz yangi platformasining batafsil tahlili.',
                    ],
                    'en' => [
                        'title'   => 'New rules in the pharmaceutical procurement market: can farma.xarid.uz reduce corruption?',
                        'excerpt' => 'Analysis of the new platform for pharmaceutical procurement.',
                        'content' => 'Detailed analysis of the new farma.xarid.uz platform.',
                    ],
                ],
            ],
            [
                'title'        => 'Почему в Узбекистане меняют подход к определению местного товара',
                'excerpt'      => 'Законодательное закрепление нового подхода к понятию «местный товар» в сфере госзакупок — как это изменит правила игры для поставщиков и заказчиков.',
                'content'      => 'Анализ нового законодательного подхода к определению местного товара в системе государственных закупок Узбекистана.',
                'image'        => 'news/seed_17.png',
                'is_featured'  => false,
                'category'     => 'legislation',
                'source'       => 'gazeta.uz',
                'source_url'   => 'https://www.gazeta.uz/ru/2026/03/24/uzbekexpertiza/',
                'tags'         => ['законодательство', 'реформа', 'госзакупки'],
                'views'        => 810,
                'published_at' => '2026-03-24',
                'translations' => [
                    'uz' => [
                        'title'   => 'Nima uchun O\'zbekistonda mahalliy tovarni aniqlashga yondashuv o\'zgartirilmoqda',
                        'excerpt' => 'Davlat xaridlari sohasida "mahalliy tovar" tushunchasiga yangi yondashuv.',
                        'content' => 'O\'zbekiston davlat xaridlari tizimida mahalliy tovarni aniqlashning yangi qonuniy yondashuvini tahlil qilish.',
                    ],
                    'en' => [
                        'title'   => 'Why Uzbekistan is changing the approach to defining local goods',
                        'excerpt' => 'Legislative consolidation of a new approach to the concept of "local goods" in public procurement.',
                        'content' => 'Analysis of the new legislative approach to defining local goods in Uzbekistan\'s public procurement system.',
                    ],
                ],
            ],
        ];

        foreach ($articles as $data) {
            NewsArticle::updateOrCreate(
                ['title' => $data['title']],
                $data,
            );
        }
    }
}
